apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/one-touch-provisioning/otp-gitops/setup/argocd-operator?ref=master
patches:
  - path: patch-channel.yaml
    target:
      kind: Subscription
      name: openshift-gitops-operator